[api_keys]
serpapi = "65d17ee731b9c0f396b7037cfc13af98ed8bae44a326a2c2c569679f3fec52c8"
mapbox = "pk.eyJ1IjoibWFya2JvZ29yYWQiLCJhIjoiY21jbHhhdnY1MGcxNzJrcHhvbTFob2QyYyJ9.LWtFtVSYdCvR-KIqu5vrzg"
max_results = 50
